version: 2

sources:
  - name: bq_steam
    # Eğer projenizde database ve schema tanımları buradaysa onlara dokunma, aynen kalsın
    tables:
      - name: history
      - name: achievements
      - name: games
      - name: prices  # İşte tam olarak buraya ekliyoruz!